import Head from "next/head";
import Paper from "@mui/material/Paper";

const Member = () => {
  return (
    <>
      <Head>
        <title>Contact List</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </>
  );
};

export default Member;
