import Head from "next/head";
import Search from "../components/Search";
import Contact from "../components/Contacts";
import Container from "@mui/material/Container";
import Grid from "@mui/material/Grid";
import Paper from "@mui/material/Paper";
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import Typography from "@mui/material/Typography";
import styles from "@/styles/Home.module.css";
import axios from "axios";

export const getStaticProps = async (context) => {
  const fetch = await axios("http://localhost:3000/api/contacts");
  const contacts = await fetch.data;
  return {
    props: {
      contacts,
    },
  };
};

export default function Home({ contacts }) {
  return (
    <>
      <Head>
        <title>Contact List</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Paper>
        <Typography variant='h1' align='center' pt={2} mb={3}>
          لیست مخاطبان
        </Typography>
        <Container
          maxWidth='xl'
          sx={{
            minHeight: "100vh",
          }}>
          <Grid container spacing={2}>
            <Grid item xs={12} sm={7} md={5}>
              <Card elevation={7}>
                <CardContent>
                  <Search />
                  <Contact contacts={contacts} />
                </CardContent>
              </Card>
            </Grid>
            <Grid item sm={5} md={7}>
              <div className={styles.image}></div>
            </Grid>
          </Grid>
        </Container>
      </Paper>
    </>
  );
}
